// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpiUkPI19n08GyeW2ghNDx_GOA0ZlabUE',
    appId: '1:679007550491:web:7f8178c8f7d5b5fee78cbe',
    messagingSenderId: '679007550491',
    projectId: 'agvaapp',
    authDomain: 'agvaapp.firebaseapp.com',
    storageBucket: 'agvaapp.appspot.com',
    measurementId: 'G-WPFMM6VK6X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGeXq1HUM6_idigSAbWHolMNCdbjXTFJ8',
    appId: '1:679007550491:android:3a7d4bfafbaaa9f1e78cbe',
    messagingSenderId: '679007550491',
    projectId: 'agvaapp',
    storageBucket: 'agvaapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm3n13a6s-G8PisCTFQzcr54EinUuGz3k',
    appId: '1:679007550491:ios:1adbd1b31f8a21e7e78cbe',
    messagingSenderId: '679007550491',
    projectId: 'agvaapp',
    storageBucket: 'agvaapp.appspot.com',
    iosBundleId: 'com.example.agvaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAm3n13a6s-G8PisCTFQzcr54EinUuGz3k',
    appId: '1:679007550491:ios:8eb83a00f25bf6d2e78cbe',
    messagingSenderId: '679007550491',
    projectId: 'agvaapp',
    storageBucket: 'agvaapp.appspot.com',
    iosBundleId: 'com.example.agvaApp.RunnerTests',
  );
}
